#!/usr/bin/env perl

use strict; use warnings;

my $requested = shift;

chomp(my @remotes = `git remote -v`);

my ($remote) = grep { /^$requested/ && /\(push\)/ } @remotes;

$remote or die "$requested: not a push remote\n";
$remote = (split ' ', $remote)[1];

my ($url, $path) = split /:/, $remote;

$url =~ m{/} and die "$remote: not a hostname\n";

exec 'ssh', '-t', $url, "CDTO=$path bash; :"
